### PR TITLE
websocket support ipv6

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
@stammen Could you please update libwebsockets for windows platforms?

Background information:

Apple required to support IPv6-only Networks since June 1, 2016, can refer to [the issue](https://github.com/cocos2d/cocos2d-x/issues/15629) for detail information. I modified compiling options of libwebsocket to support ipv6 in [this PR](https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/110).

**Comment by stammen** [comment]
@minggo Yes I will update libwebsockets.

**Comment by minggo** [comment]
Thanks.

**Comment by minggo** [comment]
@stammen all other platforms are fixed, i will create a new release when windows related platforms are added. Can i know when you can finish it because June 1 is nearly.

**Comment by stammen** [comment]
I am planning on fixing this Wednesday night or Thursday morning. I have an internal Microsoft conference until then.

Sent from Outlookhttp://aka.ms/weboutlook

**Comment by minggo** [comment]
Got it.
Thanks.

**Comment by stammen** [comment]
@minggo ipv6 is not available for windows platforms

From cmakelists.txt line 199:

``` c++

if (WIN32)
        .....
    if (LWS_IPV6)
        set(LWS_IPV6 OFF)
        message(WARNING "IPv6 does not currently work on Windows!")
    endif()
else()
```

**Comment by minggo** [comment]
Ok, so let use keep it as it is since windows platforms doesn't require IPv6-only supporting.
Thanks.

**Pull request merged**
