### PR TITLE
Compiled libwebp (win32) with /MD option.

### PR DESCRIPTION
**Pull request by cpascal**
Other 3rd party libraries and cocos2d-x projects are compiled with /MD, but libwebp is compiled with /MT option. So now it doesn't conflict and doesn't need to ignore libcmt.lib file.

### CODE REVIEW

**Comment by zilongshanren** [comment]
@cpascal 
What's the version of libjpeg and libwebp in this PR?

**Comment by cpascal** [comment]
@andyque I'm so sorry I'm responsing late..

I used jpeg-9a (public version from www.ijg.org), I know old binary was jpeg-9.
But I checked by diffing deep-check public header - jpeglib.h, jmorecfg.h and jconfig.h (In fact, I checked every cpp/h).. There was no modified function declartions nor enum-reorder, ...
 in the public headers. So I just used libjpeg-9a binary instead of libjpeg-9..

Anyway, I'll do with libjpeg-9 if you want.

**Comment by cpascal** [comment]
@andyque  And about libwebp, it's libwebp v0.2.1
source downloaded from https://chromium.googlesource.com/webm/libwebp/+/v0.2.1
my git repository with libwebp.. https://github.com/cpascal/libwebp

**Comment by zilongshanren** [comment]
@cpascal  We will resolve the 3rd party libraries issue on v4. So currently I will choose to close your PR.
Thanks.

**Pull request closed without merging**
