### PR TITLE
Support multiple build configurations

### PR DESCRIPTION
**Pull request by crazyhappygame**
Support multiple configurations
https://cmake.org/cmake/help/v3.16/variable/CMAKE_CONFIGURATION_TYPES.html#variable:CMAKE_CONFIGURATION_TYPES
https://cmake.org/cmake/help/v3.16/prop_tgt/MAP_IMPORTED_CONFIG_CONFIG.html

### CODE REVIEW

**Comment by crazyhappygame** [comment]
@minggo could you merge it?

BTW What about branch v3? Do you have plans to release next 3.17.3 or 3.18 version?

**Comment by minggo** [comment]
@crazyhappygame please update v3 too.
@PatriceJiang please take a look.

**Review by PatriceJiang — APPROVED** [review]

**Comment by minggo** [comment]
@crazyhappygame why only these libraries should be changed? What about other libraries?

**Comment by crazyhappygame** [comment]
@minggo only those libs have debug/release version
IMPORTED_LOCATION_DEBUG
IMPORTED_LOCATION_RELEAS
in others there is 
IMPORTED_LOCATION

Ok. I will create PR for v3

**Pull request merged**
