### PR TITLE
^fix issue that can't unzip an encrypted file on android 64bit

### PR DESCRIPTION
**Pull request by deyongzhong**

### CODE REVIEW

**Comment by minggo** [comment]
What's the real problem? Why it can not work on Android 64bit?

**Comment by deyongzhong** [comment]
May be caused by type conversion error data loss, once the file has a password, it can not be decompressed successfully on the android 64-bit architecture. After this modification, it can be decompressed correctly.

**Comment by minggo** [comment]
Thanks. It seems it is related to https://discuss.cocos2d-x.org/t/zlib-have-some-bug-in-arm64-v8a/46660/10. I am asking the developers to test it too.

**Comment by minggo** [comment]
@deyongzhong some developer said only change CRC32 to `#define CRC32(c, b) ((*(get_crc_table()+(((int)(c) ^ (b)) & 0xff))) ^ ((c) >> 8))` can work.

**Comment by PatriceJiang** [comment]
@deyongzhong  Would you please resolve the conflicts?

**Review by PatriceJiang — APPROVED** [review]

**Comment by minggo** [comment]
unzip is updated to 2.0, so should check if it is resolved.

**Comment by PatriceJiang** [comment]
@minggo The issue is fixed by upgrading unzip and this pr can be closed.

**Pull request closed without merging**
