### PR TITLE
Upgrade openssl to 1.0.2g and curl to 7.48 on other platforms

### PR DESCRIPTION
**Pull request by zilongshanren**
@stammen  I have upgraded win32, mac and iOS, but I don't know how to compile static libs for Win10, WinRT and WP8.1, could you help please?

thanks.

### CODE REVIEW

**Comment by stammen** [comment]
@zilongshanren I will take a look. I will also add the build scripts to cocos2d-x-3rd-party-libs-src.

**Comment by zilongshanren** [comment]
@stammen  Thanks very much!

**Comment by stammen** [comment]
@zilongshanren The updated winrt libs for curl, openssl, zlib and angle are in PR https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/215

**Comment by zilongshanren** [comment]
@stammen  thanks.

**Comment by zilongshanren** [comment]
https://github.com/cocos2d/cocos2d-x/issues/15359

**Pull request merged**
