### PR TITLE
3.17 version third-party OHOS adaptation

### PR DESCRIPTION
**Pull request by IceBBBBB**

### CODE REVIEW

**Comment by minggo** [comment]
- Why add entry.cpp?
- Is freetype/prebuilt/ohos/Android.mk needed?
- Missing poly2tri、spidermonkey、sqlite3、xxtea、zlib prebuilt lib, and are they needed?
- Websockets supports armeabi-v7a and x86, are they needed?

**Comment by IceBBBBB** [comment]
> * Why add entry.cpp?
> * Is freetype/prebuilt/ohos/Android.mk needed?
> * Missing poly2tri、spidermonkey、sqlite3、xxtea、zlib prebuilt lib, and are they needed?
> * Websockets supports armeabi-v7a and x86, are they needed?

poly2tri、spidermonkey、sqlite3、xxtea、zlib No need for precompiled libraries.
Other modified.

**Comment by minggo** [comment]
> poly2tri、spidermonkey、sqlite3、xxtea、zlib No need for precompiled libraries.

Can i know why?

**Comment by IceBBBBB** [comment]
> > poly2tri、spidermonkey、sqlite3、xxtea、zlib No need for precompiled libraries.
> 
> Can i know why?

Some libraries are not used on the HarmonyOS platform, and some official website codes also use the source code (poly2tri).

**Comment by minggo** [comment]
> Some libraries are not used on the HarmonyOS platform

Then why modify the makefile?

**Comment by IceBBBBB** [comment]
> > Some libraries are not used on the HarmonyOS platform
> 
> Then why modify the makefile?

ok  removed

**Pull request merged**
