### PR TITLE
update chipmunk lib

### PR DESCRIPTION
**Pull request by xiaofeng11**
update chipmunk lib for win32 to support both libcocos2dx & libjscocos2dx compiled as dll
update libchipmunk lib for MacOSX to support 32 bit project

@ricardoquesada @zilongshanren Please review this PR

### CODE REVIEW

**Comment by zilongshanren** [comment]
@ricardoquesada  I'm fine  with this PR, thoughts?

**Comment by pandamicro** [comment]
@ricardoquesada v3.11 alpha needs this PR, please take a look

**Comment by ricardoquesada** [comment]
yep. looks good to me.
@xiaofeng11 could you send me the patch or diff ? I want to add these changes to "cocos2d-x-3rd-party-src" repo.

**Comment by xiaofeng11** [comment]
@ricardoquesada I have mail the file I changed to you, please check your mails

**Comment by ricardoquesada** [comment]
For reference, I recently added the `CP_EXPORT` to `cpShapeGetMass` in this PR:
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/commit/597af32bcfb0f8931544d950d250ffa6cd125072

What's missing the function that you added.
Please, send a PR to `cocos2d-x-3rd-party-src`... I think I did like 95% of the job... You just need update the the cocos2d_winrt.patch file.
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/blob/v3/contrib/src/chipmunk/cocos2d_winrt.patch

Thanks.

**Comment by ricardoquesada** [comment]
ouch, this shouldn't have been merged until the patch was sent to 3rd-party-libs-src.

that is the policy: No merges in "bin" if there is not a patch in "src" that reproduces the bin.

Please, revert the merge until the patch is applied in "src". thanks.... 

... or just make sure that the patch is sent... otherwise the risk is that these libs are going to be overwritten the next time we update chipmunk

**Pull request merged**
