### PR TITLE
Enabled websockets SSL support (android and ios)

### PR DESCRIPTION
**Pull request by igorzel**
Websockets binaries built with SSL support. Updated: android and ios.

Related to this
https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/61

### CODE REVIEW

**Comment by zilongshanren** [comment]
@igorzel 
Thanks, I will test your PR and give you feedback.

**Comment by zilongshanren** [comment]
@igorzel 
Should we also change the header files here?

**Comment by igorzel** [comment]
@zilongshanren no we shouldn't change header. I just rebuilt binaries with the same version of library. Please take in consideration my comment from here https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/61 :

## Added support of self signed certificates for websockets with SSL

**By default it is disabled**. This change allows to connect to web socket server with self signed
certificate. This feature can be useful for debugging. To enable it uncomment line 15 in websockets/rules.mak. For example: with this patch you will be able to connect to **wss://echo.websocket.org** (wss means - connection with SSL). 
**THIS FEATURE MUST BE DISABLED IN PRODUCTION!**

It means that you will not be able to test it with something like **wss://echo.websocket.org**. Let me know if we need binaries built with this patch.

**Comment by zilongshanren** [comment]
@igorzel 

When I'm trying to compile websockets with ssl support, the compile scripts gives me the following error:

```
Generating SSL Certificates for the test-server...
CMake Warning at CMakeLists.txt:667 (message):
  !!! Failed to generate SSL certificate for Test Server!!!:

  OpenSSL return code = Bad CPU type in executable
```

What's the issue here?

BTW: I could build openssl without any issues.

Thanks.

**Comment by igorzel** [comment]
@zilongshanren 
I haven't seen this problem before. Can you please show me full build command which you are using (with platform, mode, etc)? 
I tried to build it on linux (Ubuntu 14.04) and OSX (10.10.5). What OS are you using?

**Comment by zilongshanren** [comment]
@igorzel 
The issue was gone after I did a refresh rebuild. Thanks for your reply.

**Pull request closed without merging**
