### PR TITLE
rebuild all libs for android with clang+libc++.

### PR DESCRIPTION
**Pull request by minggo**
remove armeabi since it is deprecated and will be removed in r17
all libs are built with API 14 except arm64 since arm64 is supported since API 21

### CODE REVIEW

**Comment by madebymozart** [comment]
Beautiful! @minggo great job

**Comment by minggo** [comment]
thanks, the corresponding script modification is: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src/pull/160

**Comment by Priority10** [comment]
Cool!
When will it be merged?

**Comment by Priority10** [comment]
❤️ ❤️ ❤️

**Pull request merged**
