### PR TITLE
3.1version third-party OHOS adaptation

### PR DESCRIPTION
**Pull request by IceBBBBB**

### CODE REVIEW

**Comment by minggo** [comment]
- Openssl、zlib supports x86 and armeabi-v7a、are they needed？

**Comment by IceBBBBB** [comment]
> * Openssl、zlib supports x86 and armeabi-v7a、are they needed？

zlib removed  x86 and armeabi-v7a, openssl not found

**Comment by minggo** [comment]
Openssl and other new libs includes android and other platforms. I think they are not needed as other platforms don't use them.

**Comment by IceBBBBB** [comment]
> Openssl and other new libs includes android and other platforms. I think they are not needed as other platforms don't use them.

ok,modified.

**Pull request merged**
