### PR TITLE
upgrade curl to 7.50.0

### PR DESCRIPTION
**Pull request by minggo**
now only update for iOS, mac and android

### CODE REVIEW

**Comment by minggo** [comment]
@stammen could you please update other platforms?

**Comment by stammen** [comment]
@minggo I will update the windows 10 and 8.1 platforms.

**Comment by minggo** [comment]
@stammen thanks

**Comment by stammen** [comment]
@minggo https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src has not been updated to curl version 7.50.0.

**Comment by stammen** [comment]
@minggo I updated the windows 10 and 8.1 platforms to CURL  v7.50.0 in PR https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/242

**Comment by minggo** [comment]
Thanks @stammen

**Pull request merged**
