### PR TITLE
update win32 projects for Visual Studio 2013

### PR DESCRIPTION
**Pull request by zawasp**
Remove warnings when building with Visual Studio 2013.

### CODE REVIEW

**Comment by dumganhar** [comment]
Hi @zawasp 
Thanks for your contribution. Could you tell us what the warnings are?

**Comment by dumganhar** [comment]
This repo is only for 3rd party prebuilt libraries now. I removed the box2d and chipmunk source codes. We will create a `cocos2d/cocos2d-x-3rd-party-src` for this. And the prebuilt libraries of box2d, chipmunk will be added to this repo. 
BTW, this repo will be renamed to `cocos2d/cocos2d-x-3rd-party-bin`.

**Comment by zawasp** [comment]
Hi @dumganhar, there are 2 problems with VS 2013: first it asks to upgrade VC++ compiler and libraries for all projects (including cocos2d-x ones - for those projects I made a separate commit). If you don't upgrade, the projects can't be built:

"error MSB8020: The build tools for Visual Studio 2010 (Platform Toolset = 'v100') cannot be found. To build using the v100 build tools, please install Visual Studio 2010 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution...".

If you let it upgrade, you get C4005 warnings all over the place:

`c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (..\base\atitc.cpp)
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
1>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (..\base\atitc.cpp)
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'
1>  CCConsole.cpp
1>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\sal_supp.h(57): warning C4005: '__useHeader' : macro redefinition (..\base\CCConsole.cpp)
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2886) : see previous definition of '__useHeader'
1>c:\program files (x86)\microsoft sdks\windows\v7.1a\include\specstrings_supp.h(77): warning C4005: '__on_failure' : macro redefinition (..\base\CCConsole.cpp)
1>          C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\sal.h(2896) : see previous definition of '__on_failure'`

The commit fixes this manually, by using V12 Visual Studio toolset.
I will make the changes for `cocos2d/cocos2d-x-3rd-party-src`

**Comment by dumganhar** [comment]
OK, thank you. :)

**Pull request closed without merging**
