### PR TITLE
v3.11 build winrt versions with correct definition of CP_EXPORT

### PR DESCRIPTION
**Pull request by stammen**
This PR fixes issue https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/pull/206#issuecomment-202660479.

CP_EXPORT is not correct for winrt and win32. We are building chipmunk as a static lib but the CP_EXPORT is for a DLL.

The win32 build of chipmunk should also be fixed and CP_EXPORT corrected for win32.

@minggo  @ricardoquesada @zilongshanren This fix is needed for v3.11 as it fixes the broken Windows 8.1 ARM JavaScript builds which are not tested by your Jenkins CI (it builds only the win32 version)

### CODE REVIEW

**Comment by stammen** [comment]
@minggo  @ricardoquesada @zilongshanren This fix is needed for v3.11 as it fixes the broken Windows 8.1 ARM JavaScript builds which are not tested by your Jenkins CI (it builds only the win32 version)

**Comment by minggo** [comment]
Thanks @stammen .
@zilongshanren Can we also add windows 8.1 ARM Javascript in our jenkins CI?

**Comment by minggo** [comment]
And i created deps-91.

**Comment by stammen** [comment]
@minggo Thanks. I will update config.json in cocos2d-x and make a pull request.

**Pull request merged**
