### PR TITLE
Remove incompatible API 'unzOpenBuffer' width minizip-1.2.0

### PR DESCRIPTION
**Pull request by halx99**

### CODE REVIEW

**Comment by minggo** [comment]
Will it break compatibility?

**Comment by halx99** [comment]
It's only used for ZipUtils, and it's behavior incorrect when we upgrade minizip to 1.2.0

**Comment by minggo** [comment]
Ok, it is merged, v3-deps-167 is released. Please update it in cocos2d-x.

**Comment by halx99** [comment]
ok

**Pull request merged**
