### PR TITLE
add bullet library

### PR DESCRIPTION
**Pull request by super626**

### CODE REVIEW

**Comment by zilongshanren** [comment]
Why not provide prebuilt version instead of plain source code? And what's the version of bullet library? where do you get these source code, thanks?

**Comment by super626** [comment]
v2.82

**Comment by super626** [comment]
You can get it here, we did a little modification on the source code.
https://github.com/bulletphysics/bullet3/releases/tag/2.82

But I find that bullet release v2.83 two hours before.

The prebuilt version is so big, and there are many platforms to provide. So we would like to provide source code.

**Comment by zilongshanren** [comment]
@super626  According to the guide, you must add the bullet physics to https://github.com/cocos2d/cocos2d-x-3rd-party-libs-src first, then send a PR with prebuilt version to this repository.  With the cocos2d-x-3d-party-libs-src repository, it won't be very difficult to prepare the prebuilt version of bullet.

And you even modified the source code, I think it is error-prone when upgrading bullet in the future. You'd better provide a patch or discuss your modification with the bullet author and send PR to resolve the problem.  If the modification is trival for our own usage, I think it's important to provide a patch. Otherwise, nobody could maintain this library except you.

@ricardoquesada  @minggo  Thoughts?

**Pull request merged**
