### PR TITLE
support IPv6 only network

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by minggo** [comment]
@stammen I update v2 to support IPv6 only network. And because libwebsockets needs to be updated and it is not compatible with previous version, so need to update win32 and wp8 platform or it will cause compiling error with latest cocos2d-x v2 codes.

Could you please update win32 and wp8 platforms of libwesockets?
Thanks.

**Comment by stammen** [comment]
@minggo  I will do this on Thursday morning.

**Comment by minggo** [comment]
Thanks.

**Comment by stammen** [comment]
@minggo wp8 code does not need to be updated. It uses its own webobject class in extensions\network\WebSocketWinRT.cpp.

**Comment by minggo** [comment]
@stammen Did you mean v2 branch? And how about windows platform?

**Comment by stammen** [comment]
@minggo: Yes I mean the v2 branch. I do not build the win32 libs. Up to now I have just built the WinRT platforms. Who is the person who built the win32 libs?

**Comment by minggo** [comment]
But v2 branch doesn't have winrt support: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/tree/v2/external/libwebsockets.

I don't know who build win32 libs, may be i can copy from v3 branch.

**Comment by stammen** [comment]
@minggo WinRT platforms = Windows Phone 8.0, WinRT 8.0, Windows 8.1-Universal (Phone and Store), Windows 10 UWP. 

WinRT = Windows Runtime.

**Comment by minggo** [comment]
@stammen Good to know, thanks.

**Comment by minggo** [comment]
But there is libs required for WP8(WinRT), and you said 

> wp8 code does not need to be updated. It uses its own webobject class in extensions\network\WebSocketWinRT.cpp.
> 
> WinRT platforms = Windows Phone 8.0
> 
>  Up to now I have just built the WinRT platforms.

I am confused. So will you build libs for WP8(WinRT)?

**Comment by stammen** [comment]
@minggo: There is no need to update V2 for WP8. It uses its own webobject class in extensions\network\WebSocketWinRT.cpp which uses the old wp8 websocket build. There was no websocket support for windows store 8.0.

**Comment by minggo** [comment]
Got it. It is strange why there is WP8 libs there. Ok, i will test windows with v3 branch.

Thanks.

**Pull request merged**
